<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Color;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all()->keyBy('slug');
        $colors = Color::all();

        // Danh sách 35 sản phẩm rèm cao cấp chia đều vào 7 danh mục sử dụng ảnh rèm thực tế
        $products = [
            // ==========================================
            // DANH MỤC 1: RÈM VẢI CAO CẤP (rem-vai-cao-cap) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Vải Gấm Bỉ Cao Cấp Melbourne',
                'sku' => 'RV-MEL-01',
                'slug' => 'rem-vai-gam-bi-cao-cap-melbourne',
                'short_description' => 'Vải dệt 3 lớp nhập khẩu Bỉ, khả năng cản sáng 100%, chống bám bụi và chống co rút.',
                'description' => 'Rèm vải gấm Melbourne là sự lựa chọn số 1 cho các căn biệt thự và phòng khách sang trọng. Sợi vải dệt mật độ cao giúp cản nhiệt lên tới 85%, giữ căn phòng luôn mát mẻ vào mùa hè và ấm áp vào mùa đông. Đường may tỉ mỉ, phụ kiện thanh ray nhôm hợp kim chống ồn cao cấp.',
                'unit_price' => 380000,
                'sale_price' => 320000,
                'min_width' => 1.0,
                'max_width' => 6.0,
                'min_height' => 1.5,
                'max_height' => 4.5,
                'main_image' => 'images/products/rem-vai-cao-cap-1-1.jpg',
                'material' => 'Vải Gấm Cao Cấp',
                'style' => 'Hiện Đại',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 1250,
                'sold_count' => 140,
                'categories' => ['rem-vai-cao-cap', 'rem-phong-khach'],
            ],
            [
                'name' => 'Rèm Vải Thô Linen Pháp Sang Trọng',
                'sku' => 'RV-LIN-02',
                'slug' => 'rem-vai-tho-linen-phap-sang-trong',
                'short_description' => 'Vải Linen mộc mạc nhập khẩu Pháp, tạo nét thanh lịch tự nhiên và thoáng đãng.',
                'description' => 'Rèm sợi đũi Linen cao cấp mang đến cảm giác thư thái, gần gũi thiên nhiên. Thớ vải dệt thô sang trọng, khả năng cản sáng 80%, cản nhiệt tốt và thân thiện tuyệt đối với môi trường.',
                'unit_price' => 450000,
                'sale_price' => 390000,
                'min_width' => 1.0,
                'max_width' => 5.5,
                'min_height' => 1.5,
                'max_height' => 4.0,
                'main_image' => 'images/products/rem-vai-cao-cap-3-1.jpg',
                'material' => 'Vải Linen Tự Nhiên',
                'style' => 'Bắc Âu (Scandinavian)',
                'curtain_type' => 'Rèm Vải 1 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 980,
                'sold_count' => 88,
                'categories' => ['rem-vai-cao-cap', 'rem-phong-ngu'],
            ],
            [
                'name' => 'Rèm Vải Nhung Hoàng Gia Versailles',
                'sku' => 'RV-VEL-03',
                'slug' => 'rem-vai-nhung-hoang-gia-versailles',
                'short_description' => 'Chất nhung tuyết mịn màng quý phái, cách âm và cản sáng tuyệt đối 100%.',
                'description' => 'Được chế tác từ nhung tuyết mềm mượt cao cấp, rèm Versailles tỏa sáng với ánh kim quý tộc dưới ánh đèn. Phù hợp cho không gian cổ điển, phòng chiếu phim gia đình, phòng ngủ master.',
                'unit_price' => 520000,
                'sale_price' => 460000,
                'min_width' => 1.2,
                'max_width' => 6.0,
                'min_height' => 1.8,
                'max_height' => 4.2,
                'main_image' => 'images/products/rem-vai-cao-cap-4-1.jpg',
                'material' => 'Nhung Tuyết Cao Cấp',
                'style' => 'Tân Cổ Điển',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 740,
                'sold_count' => 62,
                'categories' => ['rem-vai-cao-cap', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Vải Cotton Silk Ý Tinh Tế',
                'sku' => 'RV-SILK-04',
                'slug' => 'rem-vai-cotton-silk-y-tinh-te',
                'short_description' => 'Sự kết hợp hoàn mỹ giữa sợi Cotton tự nhiên và tơ lụa Silk óng ả từ Ý.',
                'description' => 'Vải dệt mật độ cao chống bám bụi bẩn, tạo sóng rèm suôn mượt mềm mại không bị gãy nếp. Đem lại không gian sống thanh lịch và đẳng cấp chuẩn phong cách châu Âu.',
                'unit_price' => 490000,
                'sale_price' => 430000,
                'min_width' => 1.0,
                'max_width' => 5.0,
                'min_height' => 1.5,
                'max_height' => 3.8,
                'main_image' => 'images/products/rem-vai-cao-cap-depo-modero-2.jpg',
                'material' => 'Cotton Silk Ý',
                'style' => 'Hiện Đại',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => false,
                'is_featured' => false,
                'is_new' => true,
                'view_count' => 510,
                'sold_count' => 45,
                'categories' => ['rem-vai-cao-cap', 'rem-phong-khach'],
            ],
            [
                'name' => 'Rèm Vải Jacquard Hoa Văn Nổi Cổ Điển',
                'sku' => 'RV-JAC-05',
                'slug' => 'rem-vai-jacquard-hoa-van-noi-co-dien',
                'short_description' => 'Kỹ thuật dệt Jacquard tinh xảo dập nổi họa tiết hoa văn hoàng gia chìm quý phái.',
                'description' => 'Từng đường kim mũi chỉ dệt nổi tạo chiều sâu không gian ấn tượng. Vải dày dặn 350g/m², bền màu trên 15 năm, không xù lông và dễ vệ sinh giặt ủi.',
                'unit_price' => 420000,
                'sale_price' => 370000,
                'min_width' => 1.0,
                'max_width' => 6.0,
                'min_height' => 1.5,
                'max_height' => 4.0,
                'main_image' => 'images/products/rem-vai-cao-cap-wego-han-quoc-12.jpg',
                'material' => 'Vải Dệt Jacquard',
                'style' => 'Cổ Điển',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 820,
                'sold_count' => 74,
                'categories' => ['rem-vai-cao-cap', 'rem-biet-thu-chung-cu'],
            ],

            // ==========================================
            // DANH MỤC 2: RÈM PHÒNG KHÁCH (rem-phong-khach) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Phòng Khách 2 Lớp Voan Thêu Sen Vàng',
                'sku' => 'RPK-VOAN-06',
                'slug' => 'rem-phong-khach-2-lop-voan-theu-sen-vang',
                'short_description' => 'Bộ rèm 2 lớp cao cấp kết hợp voan tơ thêu họa tiết hoa sen vàng tinh tế.',
                'description' => 'Sản phẩm bán chạy nhất cho phòng khách biệt thự và nhà phố. Lớp voan trắng nhẹ nhàng lọc ánh sáng lung linh, lớp vải chính cản sáng cản nhiệt tuyệt đối.',
                'unit_price' => 550000,
                'sale_price' => 480000,
                'min_width' => 1.5,
                'max_width' => 7.0,
                'min_height' => 2.0,
                'max_height' => 4.5,
                'main_image' => 'images/products/rem-cua-cao-cap-23.jpg',
                'material' => 'Gấm Thổ Cẩm & Voan Thêu',
                'style' => 'Tân Cổ Điển',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 2400,
                'sold_count' => 310,
                'categories' => ['rem-phong-khach', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Phòng Khách Biệt Thự Phong Cách Bắc Âu',
                'sku' => 'RPK-SCAN-07',
                'slug' => 'rem-phong-khach-biet-thu-phong-cach-bac-au',
                'short_description' => 'Tone màu be sáng mộc mạc Scandinavian, tạo cảm giác mở rộng diện tích phòng khách.',
                'description' => 'Thiết kế định vị sóng rèm âm trần đều tăm tắp. Phụ kiện ray bi trượt êm ái, kéo nhẹ tay không gây tiếng ồn, mang lại sự thư thái tối đa.',
                'unit_price' => 480000,
                'sale_price' => 420000,
                'min_width' => 1.2,
                'max_width' => 6.5,
                'min_height' => 1.8,
                'max_height' => 4.0,
                'main_image' => 'images/products/rem-cua-cao-cap-28.jpg',
                'material' => 'Linen Pha Cotton',
                'style' => 'Bắc Âu (Scandinavian)',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => false,
                'is_new' => false,
                'view_count' => 1650,
                'sold_count' => 195,
                'categories' => ['rem-phong-khach', 'rem-vai-cao-cap'],
            ],
            [
                'name' => 'Rèm Cửa Sổ Phòng Khách Tone Xám Ghi Hiện Đại',
                'sku' => 'RPK-GRAY-08',
                'slug' => 'rem-cua-so-phong-khach-tone-xam-ghi-hien-dai',
                'short_description' => 'Gam xám ghi thanh lịch chuẩn xu hướng nội thất hiện đại Minimalist.',
                'description' => 'Được dệt từ sợi tổng hợp chống co rút và bền màu dưới ánh nắng mặt trời gắt. Phù hợp cho cửa sổ lớn hoặc vách kính phòng khách.',
                'unit_price' => 390000,
                'sale_price' => 340000,
                'min_width' => 1.0,
                'max_width' => 5.0,
                'min_height' => 1.5,
                'max_height' => 3.5,
                'main_image' => 'images/products/rem-cua-cao-cap-29.jpg',
                'material' => 'Vải Dệt Sợi Tổng Hợp Cao Cấp',
                'style' => 'Hiện Đại',
                'curtain_type' => 'Rèm Vải 1 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 1340,
                'sold_count' => 160,
                'categories' => ['rem-phong-khach', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Cửa Chính Biệt Thự Tân Cổ Điển Royal',
                'sku' => 'RPK-ROYL-09',
                'slug' => 'rem-cua-chinh-biet-thu-tan-co-dien-royal',
                'short_description' => 'Mẫu rèm vương giả đính kèm yếm sò và tua rua hạt ngọc thủ công cao cấp.',
                'description' => 'Tác phẩm may đo nghệ thuật dành riêng cho các đại sảnh biệt thự, lâu đài. Yếm quả sò xếp nếp thủ công tinh xảo, chất vải dệt gấm dày dặn tôn lên vẻ uy nghi của gia chủ.',
                'unit_price' => 680000,
                'sale_price' => 590000,
                'min_width' => 2.0,
                'max_width' => 8.0,
                'min_height' => 2.5,
                'max_height' => 5.0,
                'main_image' => 'images/products/rem-cua-cao-cap-31.jpg',
                'material' => 'Gấm Thêu Chỉ Vàng',
                'style' => 'Cổ Điển Hoàng Gia',
                'curtain_type' => 'Rèm Nữ Hoàng Tân Cổ Điển',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 1890,
                'sold_count' => 92,
                'categories' => ['rem-phong-khach', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Thông Tầng Phòng Khách Tự Động Smart',
                'sku' => 'RPK-SMART-10',
                'slug' => 'rem-thong-tang-phong-khach-tu-dong-smart',
                'short_description' => 'Hệ rèm thông tầng chiều cao lên tới 7m tích hợp động cơ điều khiển qua Smartphone.',
                'description' => 'Giải pháp tối thượng cho nhà phố thông tầng và penthouse. Động cơ lực kéo mạnh mẽ 2.0Nm hoạt động siêu êm ái, tương thích hoàn toàn Apple HomeKit, Google Home và Tuya.',
                'unit_price' => 850000,
                'sale_price' => 750000,
                'min_width' => 2.0,
                'max_width' => 9.0,
                'min_height' => 3.5,
                'max_height' => 7.0,
                'main_image' => 'images/products/rem-vai-thong-tang-5-768x1024.jpg',
                'material' => 'Vải Cản Sáng Định Hình Cao Cấp',
                'style' => 'Hiện Đại Thông Minh',
                'curtain_type' => 'Rèm Tự Động',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 3100,
                'sold_count' => 145,
                'categories' => ['rem-phong-khach', 'rem-biet-thu-chung-cu'],
            ],

            // ==========================================
            // DANH MỤC 3: RÈM PHÒNG NGỦ (rem-phong-ngu) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Vải Nhật Bản Chống Nắng Blackout 100%',
                'sku' => 'RPN-JPN-11',
                'slug' => 'rem-vai-nhat-ban-chong-nang-blackout-100',
                'short_description' => 'Công nghệ cản sáng Blackout 100%, tiêu chuẩn kháng khuẩn & chống cháy lan từ Nhật Bản.',
                'description' => 'Dòng rèm phòng ngủ hoàn hảo với lớp dệt cản sáng triệt để giúp bạn ngủ ngon cả ban ngày. Chất vải mềm rủ tự nhiên, không mùi độc hại, an toàn tuyệt đối.',
                'unit_price' => 460000,
                'sale_price' => 395000,
                'min_width' => 1.0,
                'max_width' => 5.0,
                'min_height' => 1.5,
                'max_height' => 3.8,
                'main_image' => 'images/products/rem-cua-cao-cap-han-quoc-nhap-khau.jpg',
                'material' => 'Vải Dệt Kháng Khuẩn Nhật Bản',
                'style' => 'Tối Giản',
                'curtain_type' => 'Rèm Vải 1 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 1980,
                'sold_count' => 280,
                'categories' => ['rem-phong-ngu', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Phòng Ngủ Phủ Cao Su Non Cách Âm Êm Ái',
                'sku' => 'RPN-SILENT-12',
                'slug' => 'rem-phong-ngu-phu-cao-su-non-cach-am-em-ai',
                'short_description' => 'Lớp phủ cao su non mặt sau giảm thiểu 40% tiếng ồn đường phố và cản nhiệt tối đa.',
                'description' => 'Giải pháp tuyệt hảo cho phòng ngủ đối diện mặt đường hoặc công trình ồn ào. Giữ nhiệt độ phòng luôn ổn định, tiết kiệm đáng kể hóa đơn tiền điện điều hòa.',
                'unit_price' => 490000,
                'sale_price' => 430000,
                'min_width' => 1.0,
                'max_width' => 5.5,
                'min_height' => 1.5,
                'max_height' => 3.5,
                'main_image' => 'images/products/rv-3.jpg',
                'material' => 'Vải Phủ Cao Su Non 3 Lớp',
                'style' => 'Hiện Đại',
                'curtain_type' => 'Rèm Vải Cản Nhiệt',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 1420,
                'sold_count' => 175,
                'categories' => ['rem-phong-ngu', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Phòng Ngủ Pastel Hàn Quốc Trẻ Trung',
                'sku' => 'RPN-PASTEL-13',
                'slug' => 'rem-phong-ngu-pastel-han-quoc-tre-trung',
                'short_description' => 'Bảng màu pastel ngọt ngào như hồng phấn, xanh mint, vàng kem nhẹ nhàng thư giãn.',
                'description' => 'Vải dệt mịn màng phong cách Hàn Quốc cho không gian phòng ngủ tươi mới, trẻ trung. Rất được ưa chuộng bởi các bạn trẻ và căn hộ chung cư studio.',
                'unit_price' => 350000,
                'sale_price' => 295000,
                'min_width' => 1.0,
                'max_width' => 4.5,
                'min_height' => 1.4,
                'max_height' => 3.2,
                'main_image' => 'images/products/rem-vai-Han-Quoc-Elogi-Home.jpg',
                'material' => 'Vải Dệt Pastel Hàn Quốc',
                'style' => 'Hàn Quốc Hiện Đại',
                'curtain_type' => 'Rèm Vải 1 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => false,
                'is_new' => true,
                'view_count' => 1100,
                'sold_count' => 130,
                'categories' => ['rem-phong-ngu', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Roman Phòng Ngủ Xếp Lớp Tinh Tế',
                'sku' => 'RPN-ROMAN-14',
                'slug' => 'rem-roman-phong-ngu-xep-lop-tinh-te',
                'short_description' => 'Kiểu dáng xếp lớp gọn gàng, tiết kiệm diện tích tối đa cho cửa sổ phòng ngủ nhỏ.',
                'description' => 'Rèm Roman sang trọng với cơ cấu thanh kẹp nhôm định hình chuẩn mực. Khi kéo lên tạo thành các nếp gấp tầng tầng lớp lớp đều đặn, cản sáng 95%.',
                'unit_price' => 380000,
                'sale_price' => 330000,
                'min_width' => 0.6,
                'max_width' => 2.5,
                'min_height' => 0.8,
                'max_height' => 2.8,
                'main_image' => 'images/products/rv-7.jpg',
                'material' => 'Vải Gấm Dày Dặn',
                'style' => 'Tối Giản Hiện Đại',
                'curtain_type' => 'Rèm Roman',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 890,
                'sold_count' => 95,
                'categories' => ['rem-phong-ngu', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Phòng Ngủ Trẻ Em Họa Tiết Ngôi Sao',
                'sku' => 'RPN-KIDS-15',
                'slug' => 'rem-phong-ngu-tre-em-hoa-tiet-ngoi-sao',
                'short_description' => 'Công nghệ cắt laser hình ngôi sao phát quang lung linh khi có ánh sáng rọi qua.',
                'description' => 'Mang cả bầu trời đêm kỳ ảo vào phòng ngủ của bé. Vải không chứa chất formaldehyde, không gây dị ứng mũi, giúp bé có không gian phát triển trí tưởng tượng phong phú.',
                'unit_price' => 320000,
                'sale_price' => 270000,
                'min_width' => 1.0,
                'max_width' => 4.0,
                'min_height' => 1.2,
                'max_height' => 3.0,
                'main_image' => 'images/products/90088255_197099101591443_6529219273473130496_n-1.jpg',
                'material' => 'Cotton Blend An Toàn',
                'style' => 'Dễ Thương (Kids)',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => false,
                'is_new' => true,
                'view_count' => 670,
                'sold_count' => 84,
                'categories' => ['rem-phong-ngu', 'rem-biet-thu-chung-cu'],
            ],

            // ==========================================
            // DANH MỤC 4: RÈM CẦU VỒNG HÀN QUỐC (rem-cau-vong-han-quoc) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Cầu Vồng Eco Modero Hàn Quốc',
                'sku' => 'RCV-MOD-16',
                'slug' => 'rem-cau-vong-eco-modero-han-quoc',
                'short_description' => 'Rèm cầu vồng chính hãng Modero Hàn Quốc, dệt từ sợi polyester 100% không mùi.',
                'description' => 'Modero là thương hiệu số 1 về rèm cầu vồng tại Việt Nam. Hai lớp vải dệt xen kẽ dải cản sáng và dải voan lưới cao cấp, vận hành êm ái, lấy sáng linh hoạt theo ý muốn.',
                'unit_price' => 520000,
                'sale_price' => 460000,
                'min_width' => 0.8,
                'max_width' => 2.8,
                'min_height' => 1.0,
                'max_height' => 3.2,
                'main_image' => 'images/products/rem-cau-vong-can-sang-3.jpg',
                'material' => 'Polyester Kháng Bụi Hàn Quốc',
                'style' => 'Bắc Âu (Scandinavian)',
                'curtain_type' => 'Rèm Cầu Vồng',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 2800,
                'sold_count' => 390,
                'categories' => ['rem-cau-vong-han-quoc', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Cầu Vồng Basic Combi Cản Sáng 85%',
                'sku' => 'RCV-COMBI-17',
                'slug' => 'rem-cau-vong-basic-combi-can-sang-85',
                'short_description' => 'Mẫu rèm cầu vồng kinh tế bán chạy, phù hợp mọi khung cửa sổ chung cư và văn phòng.',
                'description' => 'Hộp phụ kiện hợp kim nhôm sơn tĩnh điện đồng màu. Dây kéo hạt nhựa lõi dù siêu bền, chịu tải trọng lớn, bảo hành chính hãng 3 năm.',
                'unit_price' => 430000,
                'sale_price' => 375000,
                'min_width' => 0.6,
                'max_width' => 2.6,
                'min_height' => 0.8,
                'max_height' => 3.0,
                'main_image' => 'images/products/rem-cau-vong-can-sang-4.jpg',
                'material' => 'Sợi Polyester Dệt Mật Độ Cao',
                'style' => 'Hiện Đại Tối Giản',
                'curtain_type' => 'Rèm Cầu Vồng',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 1560,
                'sold_count' => 230,
                'categories' => ['rem-cau-vong-han-quoc', 'rem-cuon-van-phong'],
            ],
            [
                'name' => 'Rèm Cầu Vồng Cao Cấp Triple Shade 3 Lớp',
                'sku' => 'RCV-TRIPLE-18',
                'slug' => 'rem-cau-vong-cao-cap-triple-shade-3-lop',
                'short_description' => 'Thiết kế 3 lớp sáng tạo gồm 2 lớp voan bao bọc lá vải ngang xoay lật 180 độ.',
                'description' => 'Đỉnh cao của nghệ thuật điều chỉnh ánh sáng. Vừa có thể cuộn tròn thu gọn như rèm cuốn, vừa có thể xoay lật nghiêng lá vải như rèm sáo để đón gió trong lành.',
                'unit_price' => 690000,
                'sale_price' => 610000,
                'min_width' => 0.8,
                'max_width' => 3.0,
                'min_height' => 1.0,
                'max_height' => 3.5,
                'main_image' => 'images/products/rem-cau-vong-ket-hop-rem-to-ong-cho-cua-vom-2.webp',
                'material' => 'Vải Voan & Sợi Dệt Kháng Tĩnh Điện',
                'style' => 'Sang Trọng Đẳng Cấp',
                'curtain_type' => 'Rèm Triple Shade',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 1210,
                'sold_count' => 110,
                'categories' => ['rem-cau-vong-han-quoc', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Cầu Vồng Kháng Khuẩn Fine Plus',
                'sku' => 'RCV-FINE-19',
                'slug' => 'rem-cau-vong-khang-khuan-fine-plus',
                'short_description' => 'Công nghệ phủ ion bạc diệt khuẩn 99% bề mặt, ngăn ngừa nấm mốc và dị ứng.',
                'description' => 'Sản phẩm đạt chứng nhận chất lượng xanh quốc tế Eco-friendly. Lý tưởng cho gia đình có trẻ sơ sinh, người già hoặc người có bệnh lý về đường hô hấp.',
                'unit_price' => 580000,
                'sale_price' => 510000,
                'min_width' => 0.8,
                'max_width' => 2.8,
                'min_height' => 1.0,
                'max_height' => 3.0,
                'main_image' => 'images/products/rem-cau-vong-van-phong-6.jpg',
                'material' => 'Polyester Phủ Nano Bạc',
                'style' => 'Hiện Đại Kháng Khuẩn',
                'curtain_type' => 'Rèm Cầu Vồng',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => false,
                'is_new' => true,
                'view_count' => 940,
                'sold_count' => 87,
                'categories' => ['rem-cau-vong-han-quoc', 'rem-phong-ngu'],
            ],
            [
                'name' => 'Rèm Cầu Vồng Tự Động Động Cơ Tuya Zigbee',
                'sku' => 'RCV-AUTO-20',
                'slug' => 'rem-cau-vong-tu-dong-dong-co-tuya-zigbee',
                'short_description' => 'Tích hợp mô tơ pin sạc Lithium âm ống, điều khiển hẹn giờ mở rèm đón bình minh.',
                'description' => 'Không cần đi dây điện phức tạp, pin sạc Type-C dùng liên tục 6 tháng/lần sạc. Kết nối giọng nói tiếng Việt mượt mà qua Google Assistant và loa thông minh Maika.',
                'unit_price' => 790000,
                'sale_price' => 690000,
                'min_width' => 0.8,
                'max_width' => 3.2,
                'min_height' => 1.0,
                'max_height' => 3.5,
                'main_image' => 'images/products/rem-cau-vong-ket-hop-rem-to-ong-cho-cua-vom-3.webp',
                'material' => 'Vải Cầu Vồng Blackout Cao Cấp',
                'style' => 'Smart Home',
                'curtain_type' => 'Rèm Tự Động',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 2100,
                'sold_count' => 180,
                'categories' => ['rem-cau-vong-han-quoc', 'rem-phong-khach'],
            ],

            // ==========================================
            // DANH MỤC 5: RÈM CUỐN VĂN PHÒNG (rem-cuon-van-phong) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Cuốn Trơn Văn Phòng Chống Nắng Silver',
                'sku' => 'RC-SILV-21',
                'slug' => 'rem-cuon-tron-van-phong-chong-nang-silver',
                'short_description' => 'Rèm cuốn trơn phủ bạc phản quang, chống chói lóa màn hình máy tính, độ bền cao.',
                'description' => 'Giải pháp tối ưu chi phí cho các tòa nhà văn phòng, cơ quan, phòng họp. Mặt sau phủ lớp tráng bạc phản quang giúp cản nhiệt 100%, dễ dàng vệ sinh bằng khăn ẩm.',
                'unit_price' => 240000,
                'sale_price' => 195000,
                'min_width' => 0.6,
                'max_width' => 2.5,
                'min_height' => 1.0,
                'max_height' => 3.0,
                'main_image' => 'images/products/rc-4.jpg',
                'material' => 'Sợi Thủy Tinh Phủ PVC',
                'style' => 'Tối Giản',
                'curtain_type' => 'Rèm Cuốn',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 3200,
                'sold_count' => 620,
                'categories' => ['rem-cuon-van-phong', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Cuốn Lưới Sunscreen Lấy Sáng Tự Nhiên',
                'sku' => 'RC-SUN-22',
                'slug' => 'rem-cuon-luoi-sunscreen-lay-sang-tu-nhien',
                'short_description' => 'Lớp vải lưới chống tia UV 95%, từ bên trong nhìn ra rõ ràng nhưng bên ngoài không nhìn vào được.',
                'description' => 'Tạo không gian mở thoáng đãng cho quán café, showroom trưng bày và văn phòng làm việc sáng tạo. Không bị ngột ngạt mà vẫn chống chói nắng dịu mắt.',
                'unit_price' => 290000,
                'sale_price' => 250000,
                'min_width' => 0.8,
                'max_width' => 2.8,
                'min_height' => 1.0,
                'max_height' => 3.5,
                'main_image' => 'images/products/manh-la-doc-6-1.jpeg',
                'material' => 'Sợi Thủy Tinh Lưới Đan Sunscreen',
                'style' => 'Hiện Đại Thoáng Đãng',
                'curtain_type' => 'Rèm Cuốn Lưới',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => false,
                'is_new' => true,
                'view_count' => 1750,
                'sold_count' => 240,
                'categories' => ['rem-cuon-van-phong', 'rem-phong-khach'],
            ],
            [
                'name' => 'Rèm Cuốn Tranh 3D Văn Phòng Động Lực',
                'sku' => 'RC-3D-23',
                'slug' => 'rem-cuon-tranh-3d-van-phong-dong-luc',
                'short_description' => 'In tranh công nghệ UV độ nét cao với câu khẩu hiệu truyền cảm hứng hoặc phong cảnh hữu tình.',
                'description' => 'Biến khung cửa sổ khô khan thành bức tranh nghệ thuật sống động. Mực in UV Hàn Quốc không phai màu theo thời gian, chống nước chống ẩm tuyệt hảo.',
                'unit_price' => 360000,
                'sale_price' => 310000,
                'min_width' => 0.8,
                'max_width' => 2.4,
                'min_height' => 1.0,
                'max_height' => 2.8,
                'main_image' => 'images/products/rem-vai-cao-cap-wego-han-quoc-12.jpg',
                'material' => 'Vải Cuốn Phủ Mực UV Cao Cấp',
                'style' => 'Nghệ Thuật Tranh 3D',
                'curtain_type' => 'Rèm Cuốn In Tranh',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 860,
                'sold_count' => 78,
                'categories' => ['rem-cuon-van-phong', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Lá Dọc Văn Phòng Bản 10cm Chống Cháy',
                'sku' => 'RLD-OFF-24',
                'slug' => 'rem-la-doc-van-phong-ban-10cm-chong-chay',
                'short_description' => 'Các lá rèm dọc bản rộng 100mm xoay lật 180 độ điều tiết ánh sáng linh hoạt.',
                'description' => 'Kiểu dáng văn phòng kinh điển, giá thành cực kỳ kinh tế cho diện tích lắp đặt lớn. Chất liệu chống bám bụi, hạn chế bắt lửa, dễ dàng thay thế từng lá khi hỏng hóc.',
                'unit_price' => 210000,
                'sale_price' => 175000,
                'min_width' => 1.0,
                'max_width' => 5.0,
                'min_height' => 1.5,
                'max_height' => 4.0,
                'main_image' => 'images/products/manh-la-doc-5-1-scaled.jpg',
                'material' => 'Sợi Tổng Hợp Chống Cháy Lan',
                'style' => 'Văn Phòng Chuyên Nghiệp',
                'curtain_type' => 'Rèm Lá Dọc',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => false,
                'is_featured' => false,
                'is_new' => false,
                'view_count' => 1400,
                'sold_count' => 310,
                'categories' => ['rem-cuon-van-phong', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Cuốn Chống Nắng Kính Hướng Tây Siêu Bền',
                'sku' => 'RC-WEST-25',
                'slug' => 'rem-cuon-chong-nang-kinh-huong-tay-sieu-ben',
                'short_description' => 'Cấu tạo 4 lớp chuyên dụng cho mặt dựng kính hướng Tây chịu nhiệt độ nắng gắt.',
                'description' => 'Ngăn chặn 99% nhiệt lượng mặt trời xâm nhập vào phòng. Khung máng nhôm chịu lực dày 1.4mm, trục cuốn nhôm hợp kim chống võng rèm tối ưu.',
                'unit_price' => 280000,
                'sale_price' => 240000,
                'min_width' => 0.8,
                'max_width' => 2.6,
                'min_height' => 1.0,
                'max_height' => 3.2,
                'main_image' => 'images/products/rc-4.jpg',
                'material' => 'Sợi Thủy Tinh Cách Nhiệt Kép',
                'style' => 'Công Năng Chuyên Dụng',
                'curtain_type' => 'Rèm Cuốn Cản Nhiệt',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 2200,
                'sold_count' => 410,
                'categories' => ['rem-cuon-van-phong', 'rem-chong-nang-cach-nhiet'],
            ],

            // ==========================================
            // DANH MỤC 6: RÈM CHỐNG NẮNG CÁCH NHIỆT (rem-chong-nang-cach-nhiet) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Tổ Ong Honeycomb Cách Nhiệt Tiết Kiệm Điện',
                'sku' => 'RTO-HONEY-26',
                'slug' => 'rem-to-ong-honeycomb-cach-nhiet-tiet-kiem-dien',
                'short_description' => 'Cấu trúc ô lục giác dạng tổ ong giữ lớp đệm không khí, ngăn truyền nhiệt 95%.',
                'description' => 'Công nghệ rèm hiện đại bậc nhất hiện nay. Lớp bạc tráng bên trong khoang tổ ong cách âm cách nhiệt hoàn hảo, kéo rèm xếp gọn siêu mỏng không chiếm diện tích cửa.',
                'unit_price' => 750000,
                'sale_price' => 670000,
                'min_width' => 0.6,
                'max_width' => 3.0,
                'min_height' => 0.8,
                'max_height' => 3.5,
                'main_image' => 'images/products/rem-cau-vong-ket-hop-rem-to-ong-cho-cua-vom-2.webp',
                'material' => 'Vải Không Dệt Tráng Bạc Tổ Ong',
                'style' => 'Công Nghệ Tiên Tiến',
                'curtain_type' => 'Rèm Tổ Ong',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 3400,
                'sold_count' => 290,
                'categories' => ['rem-chong-nang-cach-nhiet', 'rem-biet-thu-chung-cu'],
            ],
            [
                'name' => 'Rèm Vải Phủ Silicon Cản Nhiệt 95% Mùa Hè',
                'sku' => 'RCN-SILI-27',
                'slug' => 'rem-vai-phu-silicon-can-nhiet-95-mua-he',
                'short_description' => 'Bề mặt phủ tráng Silicon công nghệ Đức ngăn bức xạ tia hồng ngoại sinh nhiệt.',
                'description' => 'Vải mềm mại, không bị giòn gãy hay dính bết như cao su thông thường khi phơi nắng thời gian dài. Giảm nhiệt độ phòng từ 3 đến 6 độ C so với ngoài trời.',
                'unit_price' => 480000,
                'sale_price' => 415000,
                'min_width' => 1.0,
                'max_width' => 5.5,
                'min_height' => 1.5,
                'max_height' => 3.8,
                'main_image' => 'images/products/rem-vai-cao-cap-4-1.jpg',
                'material' => 'Vải Dệt Phủ Silicon Đức',
                'style' => 'Hiện Đại Bền Bỉ',
                'curtain_type' => 'Rèm Vải Cản Nhiệt',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 1620,
                'sold_count' => 210,
                'categories' => ['rem-chong-nang-cach-nhiet', 'rem-vai-cao-cap'],
            ],
            [
                'name' => 'Rèm Gỗ Tự Nhiên Basswood Xử Lý Nhiệt',
                'sku' => 'RG-BASS-28',
                'slug' => 'rem-go-tu-nhien-basswood-xu-ly-nhiet',
                'short_description' => '100% gỗ tự nhiên sấy nhiệt chống cong vênh, tạo vẻ đẹp mộc mạc và sang trọng.',
                'description' => 'Lá gỗ rộng 50mm phủ sơn UV 3 lớp chống bay màu và chống ẩm mốc. Tỏa hương gỗ thoang thoảng tự nhiên, rất thích hợp cho phòng làm việc giám đốc và phòng khách cổ điển.',
                'unit_price' => 620000,
                'sale_price' => 540000,
                'min_width' => 0.6,
                'max_width' => 2.4,
                'min_height' => 0.8,
                'max_height' => 3.0,
                'main_image' => 'images/products/rem-cua-cao-cap-28.jpg',
                'material' => 'Gỗ Tự Nhiên Basswood Nhập Khẩu',
                'style' => 'Thuần Mộc Sang Trọng',
                'curtain_type' => 'Rèm Sáo Gỗ',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 1890,
                'sold_count' => 165,
                'categories' => ['rem-chong-nang-cach-nhiet', 'rem-phong-khach'],
            ],
            [
                'name' => 'Rèm Sáo Nhôm Sơn Tĩnh Điện Chống Ẩm Chịu Nhiệt',
                'sku' => 'RSN-ALU-29',
                'slug' => 'rem-sao-nhom-son-tinh-dien-chong-am-chiu-nhiet',
                'short_description' => 'Lá nhôm 25mm siêu nhẹ, chống nước 100%, chuyên dùng cho phòng tắm và bếp.',
                'description' => 'Không bị rỉ sét hay ẩm mốc trong môi trường độ ẩm cao. Có thể xoay lật 360 độ điều chỉnh ánh sáng và chống nhìn trộm kín đáo tuyệt đối.',
                'unit_price' => 260000,
                'sale_price' => 220000,
                'min_width' => 0.5,
                'max_width' => 2.2,
                'min_height' => 0.6,
                'max_height' => 2.5,
                'main_image' => 'images/products/rem-cau-vong-van-phong-6.jpg',
                'material' => 'Hợp Kim Nhôm Sơn Tĩnh Điện',
                'style' => 'Hiện Đại Chống Nước',
                'curtain_type' => 'Rèm Sáo Nhôm',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => false,
                'is_featured' => false,
                'is_new' => true,
                'view_count' => 780,
                'sold_count' => 95,
                'categories' => ['rem-chong-nang-cach-nhiet', 'rem-cuon-van-phong'],
            ],
            [
                'name' => 'Rèm Tổ Ong Trên Kính Giếng Trời Tự Động',
                'sku' => 'RTO-SKY-30',
                'slug' => 'rem-to-ong-tren-kinh-gieng-troi-tu-dong',
                'short_description' => 'Hệ rèm kéo ngang trên trần kính giếng trời, che nắng gay gắt từ đỉnh mái nhà.',
                'description' => 'Động cơ ray trượt chịu nhiệt độ cao trên mái kính. Giúp ngôi nhà luôn mát mẻ, bảo vệ nội thất sàn gỗ và sofa không bị bạc màu do ánh nắng giếng trời chiếu thẳng.',
                'unit_price' => 920000,
                'sale_price' => 820000,
                'min_width' => 1.0,
                'max_width' => 4.0,
                'min_height' => 1.5,
                'max_height' => 6.0,
                'main_image' => 'images/products/rem-cau-vong-ket-hop-rem-to-ong-cho-cua-vom-3.webp',
                'material' => 'Tổ Ong Tráng Bạc Kép',
                'style' => 'Giếng Trời Tự Động',
                'curtain_type' => 'Rèm Giếng Trời',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 2450,
                'sold_count' => 135,
                'categories' => ['rem-chong-nang-cach-nhiet', 'rem-biet-thu-chung-cu'],
            ],

            // ==========================================
            // DANH MỤC 7: RÈM BIỆT THỰ & CHUNG CƯ (rem-biet-thu-chung-cu) - 5 Sản phẩm
            // ==========================================
            [
                'name' => 'Rèm Biệt Thự Nữ Hoàng Cổ Điển Đính Yếm Sò',
                'sku' => 'RBT-QUEEN-31',
                'slug' => 'rem-biet-thu-nu-hoang-co-dien-dinh-yem-so',
                'short_description' => 'Đỉnh cao phong cách Hoàng Gia Pháp với yếm rèm thêu hoa văn ánh kim lộng lẫy.',
                'description' => 'Mẫu rèm trứ danh cho các căn biệt thự triệu đô. Sự kết hợp giữa vải gấm dệt chỉ vàng lấp lánh và voan thêu đính đá thủ công tạo nên vẻ đẹp tráng lệ không thể rời mắt.',
                'unit_price' => 790000,
                'sale_price' => 690000,
                'min_width' => 1.8,
                'max_width' => 8.0,
                'min_height' => 2.2,
                'max_height' => 5.0,
                'main_image' => 'images/products/rem-cua-cao-cap-31.jpg',
                'material' => 'Gấm Thêu Kim Tuyến & Yếm Lụa',
                'style' => 'Hoàng Gia Cổ Điển',
                'curtain_type' => 'Rèm Nữ Hoàng',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 2100,
                'sold_count' => 115,
                'categories' => ['rem-biet-thu-chung-cu', 'rem-vai-cao-cap'],
            ],
            [
                'name' => 'Rèm Chung Cư Căn Hộ Penthouse Sang Trọng',
                'sku' => 'RCC-PENT-32',
                'slug' => 'rem-chung-cu-can-ho-penthouse-sang-trong',
                'short_description' => 'Thiết kế định vị sóng rèm âm trần đều tăm tắp, mở rộng tầm nhìn Panorama.',
                'description' => 'Tôn vinh trọn vẹn vẻ đẹp của các căn hộ tầng cao với view nhìn triệu đô. Chất vải rủ mềm mại, cản sáng 100% khi cần sự riêng tư tuyệt đối.',
                'unit_price' => 650000,
                'sale_price' => 570000,
                'min_width' => 1.5,
                'max_width' => 7.0,
                'min_height' => 2.0,
                'max_height' => 4.2,
                'main_image' => 'images/products/rem-cua-cao-cap-23.jpg',
                'material' => 'Vải Gấm Dệt Mịn 2 Lớp',
                'style' => 'Hiện Đại Sang Trọng',
                'curtain_type' => 'Rèm Vải 2 Lớp',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 1950,
                'sold_count' => 220,
                'categories' => ['rem-biet-thu-chung-cu', 'rem-phong-khach'],
            ],
            [
                'name' => 'Rèm Sáo Gỗ Bách Hương Kháng Mối Mọt',
                'sku' => 'RSG-CEDAR-33',
                'slug' => 'rem-sao-go-bach-huong-khang-moi-mot',
                'short_description' => 'Gỗ Bách Hương đỏ tự nhiên thơm ngát, vân gỗ tuyệt mỹ, kháng mối mọt trọn đời.',
                'description' => 'Lá gỗ bản 50mm chắc chắn, chịu được khí hậu nhiệt đới ẩm gió mùa của Việt Nam. Dây thang dù dệt thổ cẩm tinh xảo mang lại nét sang trọng, đĩnh đạc cho căn nhà.',
                'unit_price' => 710000,
                'sale_price' => 630000,
                'min_width' => 0.6,
                'max_width' => 2.5,
                'min_height' => 0.8,
                'max_height' => 3.2,
                'main_image' => 'images/products/rem-vai-cao-cap-1-1.jpg',
                'material' => 'Gỗ Bách Hương Đỏ Tự Nhiên',
                'style' => 'Gỗ Quý Sang Trọng',
                'curtain_type' => 'Rèm Sáo Gỗ',
                'stock_status' => 'in_stock',
                'is_hot' => false,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => false,
                'view_count' => 1430,
                'sold_count' => 135,
                'categories' => ['rem-biet-thu-chung-cu', 'rem-chong-nang-cach-nhiet'],
            ],
            [
                'name' => 'Rèm Voan Thêu Tay Mỹ Nghệ Cung Đình',
                'sku' => 'RV-EMB-34',
                'slug' => 'rem-voan-theu-tay-my-nghe-cung-dinh',
                'short_description' => 'Họa tiết thêu tay độc bản từ các nghệ nhân làng nghề thêu truyền thống.',
                'description' => 'Mỗi mét rèm là một tác phẩm nghệ thuật kỳ công. Lớp voan tơ tằm mềm như mây, thêu hoa lá cành hoặc chim hạc phong thủy mang lại may mắn, tài lộc cho gia chủ.',
                'unit_price' => 590000,
                'sale_price' => 520000,
                'min_width' => 1.0,
                'max_width' => 6.0,
                'min_height' => 1.5,
                'max_height' => 4.5,
                'main_image' => 'images/products/rem-vai-cao-cap-3-1.jpg',
                'material' => 'Voan Tơ Tằm Thêu Tay Mỹ Nghệ',
                'style' => 'Nghệ Thuật Truyền Thống',
                'curtain_type' => 'Rèm Voan Nghệ Thuật',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => false,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 1120,
                'sold_count' => 88,
                'categories' => ['rem-biet-thu-chung-cu', 'rem-phong-khach'],
            ],
            [
                'name' => 'Rèm Tự Động Somfy Pháp Kết Nối Nhà Thông Minh',
                'sku' => 'R-SOMFY-35',
                'slug' => 'rem-tu-dong-somfy-phap-ket-noi-nha-thong-minh',
                'short_description' => 'Động cơ Somfy nhập khẩu trực tiếp từ Pháp, bảo hành chính hãng 5 năm đổi mới.',
                'description' => 'Thương hiệu động cơ rèm danh tiếng số 1 toàn cầu. Tích hợp cảm biến ánh sáng tự động đóng khi trời nắng gắt và mở khi hoàng hôn, đem đến trải nghiệm sống tiện nghi chuẩn 5 sao.',
                'unit_price' => 1150000,
                'sale_price' => 990000,
                'min_width' => 1.5,
                'max_width' => 10.0,
                'min_height' => 1.8,
                'max_height' => 6.0,
                'main_image' => 'images/products/rem-vai-thong-tang-5-768x1024.jpg',
                'material' => 'Vải Bỉ & Động Cơ Somfy France',
                'style' => 'Smart Luxury 5 Sao',
                'curtain_type' => 'Rèm Tự Động',
                'stock_status' => 'in_stock',
                'is_hot' => true,
                'is_trending' => true,
                'is_featured' => true,
                'is_new' => true,
                'view_count' => 4500,
                'sold_count' => 310,
                'categories' => ['rem-biet-thu-chung-cu', 'rem-phong-khach'],
            ],
        ];

        foreach ($products as $pData) {
            $catSlugs = $pData['categories'];
            unset($pData['categories']);

            $product = Product::updateOrCreate(
                ['slug' => $pData['slug']],
                $pData
            );

            // Gán danh mục
            $catIds = [];
            foreach ($catSlugs as $cSlug) {
                if (isset($categories[$cSlug])) {
                    $catIds[] = $categories[$cSlug]->id;
                }
            }
            $product->categories()->sync($catIds);

            // Gán màu sắc mẫu & tồn kho
            $colorSync = [];
            foreach ($colors as $cModel) {
                $colorSync[$cModel->id] = ['stock_quantity' => rand(40, 250)];
            }
            $product->colors()->sync($colorSync);
        }
    }
}
